/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-page-custom-font */

import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import Header from "../components/header/Header";
import Sidebar from '../components/sidebar/SideBar';
import { StyledContainer, Main } from './App.styles';


const Home: NextPage = () => {
  const [search, setSearch] = useState('');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto" />
      </Head>
      <Header></Header>
      <StyledContainer>
        <Sidebar />
        <Main />
      </StyledContainer>
    </div>
  )
}

export default Home
